apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-gs-ping.fullname" . }}
  labels:
    {{- include "docker-gs-ping.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.nodeExporter.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "docker-gs-ping.selectorLabels" . | nindent 4 }}
