name: Approve and Merge Dependabot's PR
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: write
  actions: write

concurrency:
  group: dependabot

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
        with:
          disable-sudo: true
          egress-policy: "audit"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Dependency Review
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
        with:
          license-check: true
          vulnerability-check: true
          fail-on-severity: "low"

      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ github.token }}

      - name: Approve and Merge PR
        uses: fastify/github-action-merge-dependabot@9e7bfb249c69139d7bdcd8d984f9665edd49020b # v3.10.1
        with:
          approve-only: false
          merge-comment: "I'm **approving** this PR because **it includes dependency update**"
          use-github-auto-merge: false
